# Generated by Django 6.0 on 2025-12-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_price', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
            ],
        ),
    ]
