# Generated by Django 6.0 on 2025-12-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
